[versions]
assertj = "3.27.7"
coroutines = "1.10.2"
gradle-maven-publish = "0.35.0"
dokka = "2.1.0"
google-annotations = "4.9.8"
guava = "33.5.0-jre"
junit = "5.13.4"
kotlin = "2.3.0"
mockito = "5.21.0"
retrofit = "3.0.0"
retromock = "1.3.0"
moshi = "1.15.2"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
google-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "google-annotations" }
google-guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retromock = { module = "com.infinum:retromock", version.ref ="retromock"}
moshi = {module = "com.squareup.moshi:moshi", version.ref = "moshi"}
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

[plugins]
dokka-plugin = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }

